name: e_commerce
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.2
  change_app_package_name: ^1.1.0
  curved_navigation_bar: ^1.0.3
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_auth: ^4.7.1
  firebase_storage: ^11.2.5
  cached_network_image: ^3.2.3
  google_sign_in: ^6.1.4
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  zoom_tap_animation: ^1.1.0
  image_picker: ^1.0.1
  provider: ^6.0.5
  http: ^1.1.0
  firebase_messaging: ^14.6.5
  persistent_bottom_nav_bar: ^5.0.2
  lottie: ^2.5.0
  shared_preferences: ^2.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  flutter_local_notifications: ^15.1.0+1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
